server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样比例，默认是0.1，即只抽取10%的数据