server:
  port: 8402
spring:
  application:
    name: hystrix-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
service-url:
  user-service: http://user-service
#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'