server:
  port: 8003
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: true #不向注册中心注册自己
    fetch-registry: true #不从注册中心取服务
    service-url:
      defaultZone: http://127.0.0.1:/8002/eureka/
  instance:
    hostname: replica2
  server:
    enable-self-preservation: false #关闭保护模式
